CREATE DATABASE pharmchan;
\c pharmchan;
CREATE USER pharmchandjango_server WITH ENCRYPTED PASSWORD 'pharmchan2024';
ALTER ROLE pharmchandjango_server SET client_encoding TO 'utf8';
ALTER ROLE pharmchandjango_server SET default_transaction_isolation TO 'read committed';
ALTER ROLE pharmchandjango_server SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE pharmchan TO pharmchandjango_server;
CREATE SCHEMA pharmchandjango_server;
GRANT USAGE ON SCHEMA pharmchandjango_server TO pharmchandjango_server;
GRANT CREATE ON SCHEMA pharmchandjango_server TO pharmchandjango_server;
